INFINITY = 10000000
# ELF HEADER CONSTANTS
PHOFF_OFFSET = 32
PHOFF_SIZE = 8
E_PHENTSIZE_OFFSET = 54
E_PHENTSIZE_SIZE = 2
E_PHNUM_OFFSET = 56
E_PHNUM_SIZE = 2

# PROGRAM HEADER CONSTANTS
PROGRAM_HEADER_TYPE_DYNAMIC = 2

P_TYPE_OFFSET = 0
P_TYPE_SIZE = 4
P_VADDR_OFFSET = 16
P_VADDR_SIZE = 8

# DYNAMIC SEGMENT
ELF64_DYN_VAR_SIZE = 8
ELF64_DYN_PTR_SIZE = 8
ELF64_DYN_SIZE = ELF64_DYN_VAR_SIZE + ELF64_DYN_PTR_SIZE

ELF64_DYN_VAR_PLTGOT = 3
